### ISSUE TITLE
accommodation 的数据类型？

### ISSUE THREAD

**Issue by zhzhzoo** [CAPU-ENG/capurace#104]
capurace.sql 中

    `accommodation` tinyint(1) NOT NULL,

application/config/constants.php 中

    $ACCOMMODATION = array(
        '0' => '不需要',
        '1' => '旅馆',
        '2' => '露营（自带帐篷）',
        '3' => '露营（租用帐篷）'
    );

**Comment by huxuan** [comment]
用到`$ACCOMMODATION`都是前台显示，在显示html和js里都应该是字符串，所以跟数据库不矛盾。

**Comment by zhzhzoo** [comment]
啊抱歉没问清楚。。。就是 $ACCOMMODATION 有 4 个选项但是 `accommodation` 只有 1 位

**Comment by JeldorPKU** [comment]
1位够了吧……一个数字？现在存储好像没有出现问题……

**Comment by zhzhzoo** [comment]
哦我错了我没有看文档。。。
