### ISSUE TITLE
点“提交，前往团体赛报名”后应该禁用按钮

### ISSUE THREAD

**Issue by goodman-capu** [CAPU-ENG/capurace#109]
不然网络慢的时候很久没有响应，人家会不停去点这个，服务器压力更大。而且最后返回很多次信息

**Comment by goodman-capu** [comment]
以及还有类似于“注册”这种需要服务器返回数据的按钮

**Comment by huxuan** [comment]
It should be a simple js work. Do you want to have a try? @goodman-capu

**Comment by cindywang319** [comment]
我来吧

**Comment by goodman-capu** [comment]
=_=电脑不在身边。。。晚上看看有什么能做的

**Comment by huxuan** [comment]
It's a good start! @goodman-capu
