### ISSUE TITLE
查看报名结果页面出现乱码的问题

### ISSUE THREAD

**Issue by cindywang319** [CAPU-ENG/capurace#111]
出现乱码的操作是这样的：首先填写所有参赛人员名单信息，并且报名好团体赛内容，然后再返回把所有人员信息给删除，这时候再点击查看报名人员资料就会出现乱码问题；而如果只删除一个或者两个参赛人员信息，结果页面也会出现php error，但是不会乱码

**Comment by goodman-capu** [comment]
以及激活账号界面也是乱码
婵�娲绘垚鍔燂紒

**Comment by JeldorPKU** [comment]
激活页面那个是纯编码问题

**Comment by JeldorPKU** [comment]
我下课了来看看……

**Comment by huxuan** [comment]
这个感觉是设计问题啊，我们本来的设计就应该是，要看报名结果，必须阅读报名须知，先报个人，再报团体，最后再看最终结果。如果报完了把个人都删了，团体又没改，当然会出现问题啦。建议是取消直接访问报名结果页面，如果真的要用url那样暴力访问，看到乱码也是自己作死啊

**Comment by cindywang319** [comment]
要人性化一点的话这时候最好报名结果页面能显示为空，能做吗……？

**Comment by huxuan** [comment]
可以倒是可以，只是加入删除了一个队中的一个人，那该怎么算呢？怎么显示都感觉怪怪的……
我来交个pr把空白的值都置空吧~

**Comment by cindywang319** [comment]
如果只删除了一个人，现在页面会把那个位置自动置空，同时顶上会有很多php error
