### ISSUE TITLE
换设备操作后有Bug

### ISSUE THREAD

**Issue by goodman-capu** [CAPU-ENG/capurace#112]
test@chexie.net账号 我的电脑登陆后 看报名界面有四个人 显示也是正常的 然后再进报名界面就只剩一个人了（之前的Cookie？）而且还可以点提交保存 保存后又乱码了

**Comment by cindywang319** [comment]
我也出过这种问题，当时好像是换浏览器就跪了

在 2015年4月16日 下午3:54，goodman-capu <notifications@github.com>写道：

> test@chexie.net账号 我的电脑登陆后 看报名界面有四个人 显示也是正常的
> 然后再进报名界面就只剩一个人了（之前的Cookie？）而且还可以点提交保存 保存后又乱码了
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CAPU-ENG/capurace/issues/112>.
>



-- 
王心怡 1100012796
北京大学 信息科学技术学院 计算机系

**Comment by huxuan** [comment]
现在的确在每个页面提交（不是暂时保存）之前，都是只是保存在本地（浏览器）的，所以这个可以说是known issue。如果只是一个人报名，或者报名之后按了提交按钮（每个页面的提交按钮，不是最终的），就应该不会出现这个问题。

**Comment by cindywang319** [comment]
即使是同一个人报名，他也有可能点开两个网页……出现乱码就挺用户不友好的

**Comment by huxuan** [comment]
只要是在同一浏览器下面操作，就应该不会有这个问题。另外这个不是乱码的那个bug……

**Comment by huxuan** [comment]
Actually I don't think this is a bug now. Feel free to reopen it if you think we have to do more about this.
