### ISSUE TITLE
[Proposal] 要不要加一个网站正在开发中的说明？

### ISSUE THREAD

**Issue by huxuan** [CAPU-ENG/capurace#117]
可以在标题栏空白的位置加一行不是太显眼的说明？万一坏了可以发邮件给我们咨询啥的？语文功底拙计，各位可以斟酌一下~

**Comment by goodman-capu** [comment]
本网站由北京大学自行车协会会员自行开发，虽经过诸多测试，但由于水平有限，无法保证不出任何差错。如在使用网站过程中遇到任何问题，请联系XXX？

**Comment by huxuan** [comment]
I don't think this proposal is useful now. Feel free to close it. @JeldorPKU

**Comment by JeldorPKU** [comment]
Fine.
