### ISSUE TITLE
Restrict access for login required page.

### ISSUE THREAD

**Issue by huxuan** [CAPU-ENG/capurace#14]
RT

**Comment by JeldorPKU** [comment]
I have already stored the user's id and `logged_in` in `/applications/controllers/user.php` lines 27 and 28. I don't know if it is proper to do so.

**Comment by JeldorPKU** [comment]
http://konyukhov.com/soft/tank_auth/ Shall we use this? @huxuan

**Comment by huxuan** [comment]
Don't worry about this, I will handle this.
