### ISSUE TITLE
Problem on updating and displaying data.

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/capurace#151]
山东大学报告的bug，操作如下：
- 插入35人，其中11人未统计到身份证号，提交时后台报错。
- 删除这11个人。
- 前往团体赛报名，发现有人未选团体赛。
- 返回修改，发现仅剩10人。
- 查看后台，丢失的11人都被处理为`deleted=1`。
使用的浏览器为360极速浏览器。

**Comment by huxuan** [comment]
丢失的不应该是35-11-10=14人么？还是我理解错了？

**Comment by JeldorPKU** [comment]
丢失的是另外14个……那11个正常删除了

**Comment by huxuan** [comment]
如果数据库里面没有任何记录，包括`deleted=1`的，那应该就是丫没有提交到服务器上，比如同时开了个人和团体两个页面啥的，这样在目前的机制下还很难避免类似的问题。

**Comment by JeldorPKU** [comment]
����������������������������������������������������������������������

**Comment by JeldorPKU** [comment]
好像仅剩10个不是删除的问题……今天又有两个高校说丢人了，于是准备修一下

**Comment by JeldorPKU** [comment]
感觉这个issue又要开了……

**Comment by JeldorPKU** [comment]
现在需要检查一下post的算法了……

**Comment by JeldorPKU** [comment]
360 browser is a SOB. ;-)
