### ISSUE TITLE
Judge if the deadline has passed.

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/capurace#157]
用于处理5.2零点之后禁止报名。
有人来做吗？我做完 #156 之后可能没工夫弄这个了，2号我要骑车去所以没法等到12点……或者你们愿意手动也行咯。

**Comment by huxuan** [comment]
到时候手动把网站关了？23333

**Comment by huxuan** [comment]
或者直接一条sql把所有user的editable改成0？

**Comment by JeldorPKU** [comment]
直接这么简单不行吧，如果是没有交费的还得告诉他们你们不用来了……

**Comment by JeldorPKU** [comment]
手动关掉的话要是他们忘记导出了就啥也看不到了

**Comment by huxuan** [comment]
那除了editable可以改我不太想的出来还有什么可以动的了……
告诉他们不用来了和忘记导出这种事情，可以让外联做……

**Comment by JeldorPKU** [comment]
是不是可以加个时间判断？以及我发现一个问题，万一他们绕开前台直接给后台post一个`array('paid'=>1)`我们就傻逼了……

**Comment by huxuan** [comment]
加个时间判断和editable=0的效果我赶脚是一样的？（如果我理解错了尽管喷我……

我们应该没有提供这个接口吧，还是我们的update写的太丧心病狂了？

**Comment by JeldorPKU** [comment]
我们的update就是直接简单粗暴一个数组啊……

**Comment by JeldorPKU** [comment]
手动手动！关闭系统的按键已经准备好了！
