### ISSUE TITLE
总负责后台

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/CAPUrace#177]
race.chexie.net/index.php/boss/

**Comment by JeldorPKU** [comment]
要求登录后能够实现以下功能：
- 查看当前所有高校注册信息以及每个高校各自的报名信息；
- 查看当着报名数据（各项比赛及后勤人数）；
- 关闭报名系统；

**Comment by huxuan** [comment]
链接用admin吧，boss觉得好鬼畜……

**Comment by JeldorPKU** [comment]
@huxuan admin已经被外联占了TAT

**Comment by huxuan** [comment]
只用一个admin就可以了，应该在微信上聊得差不多了吧~

**Comment by JeldorPKU** [comment]
Completed in #180

**Comment by huxuan** [comment]
@JeldorPKU Maybe this will save you some time ;-)
- https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by JeldorPKU** [comment]
@huxuan I just forgot to add the issue number into the commit message :-P

**Comment by huxuan** [comment]
@JeldorPKU  `git commit --amend`

**Comment by JeldorPKU** [comment]
@huxuan good idea! Gotcha~
