### ISSUE TITLE
将收费标准加入活动通知

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/CAPUrace#202]
放在报名须知里面好多人看不到，直接放在首页的活动通知吧。
紧急，4月18日之内解决。 @zhiyuecynthia

**Comment by zhiyuecynthia** [comment]
费用说明不清楚
一部分在前面说明，如下
大学生男子精英组和大众组不可兼报，二者只能报其一。只报名参加上述赛事（即教工邀请赛、大学生男子精英组、大学生男子大众组、大学生女子组、大学生接力组//这个括号里面的内容是我加的）一项者，需缴纳报名费50元（含保险和5月15日午餐）。既报名个人赛又报名团体赛者，需补缴报名费20元。例子：某队员报名大学生男子大众组，与另外3名同校车协队员组成接力组。则该名队员需缴纳报名费70元。某队员报名大学生接力组，未报名个人赛，则缴纳报名费50元。
另一部分在活动通知-》友情提示-》关于比赛
 所有组别（大学男子精英组、大学男子大众组、大学女子组、大学生接力组）需在5月15日由领队携带所有队员身份证、学生证原件以及200元/人次的电子计时器押金，到北大赛现场领取赛事套包 ，并及时下发。
（注：每个组别有一个号码和电子计时器，团体接力组共用一个号码和电子计时器，如果某队员参与大学男子精英组和大学生接力组，则其本人应缴纳 200 元的电子计时器押金，其所在接力组集体缴纳200元/组的电子计时器押金）
没有说明关于教工邀请赛的费用问题

**Comment by JeldorPKU** [comment]
Closed via #205
