### ISSUE TITLE
Check activation before confirmation.

### ISSUE THREAD

**Issue by huxuan** [CAPU-ENG/CAPUrace#206]
We should check activation before confirmation during login process. It seems that we never check the activation in current codebase.

**Related Code**: https://github.com/CAPU-ENG/CAPUrace/blob/a8d16dcd594a1b04238ea1cd43b46f1428acaaf9/application/controllers/user.php#L55

**Comment by JeldorPKU** [comment]
According to the current logic, only when the user is activated can it be confirmed. So it is not doing harm for the time being.
I agree to fix this in the next step.
