### ISSUE TITLE
Add passport as a new option for identity verification

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/CAPUrace#222]
For some foreign athletes who have no ID cards.

**Comment by Luolc** [comment]
Since we are having both ID card and passport for identity verification now, the column name and variable name `id_card` should be updated in the meantime.

**Comment by huxuan** [comment]
`sed`[1] can be helpful to replace all needs.
It should be something like `sed -i -e 's/id_card/id_number/g' *.php`.

[1] https://www.gnu.org/software/sed/manual/sed.html

**Comment by huxuan** [comment]
The only left related task is #240, right? Just want to have a confirmation.

**Comment by JeldorPKU** [comment]
Yep. And this issue can be closed now.
