### ISSUE TITLE
Activation mail not received for E-mail addresses other than 163/126.

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/CAPUrace#257]
Are there any improvements we can do?

**Comment by huxuan** [comment]
Seems that our emails are treated as spam (mostly because we do not have valid certificates from our custom email server). Maybe we still need to use some third-party email service to avoid these problem.

**Comment by JeldorPKU** [comment]
Well, it is working quite well on the server so far. I will seek for some solutions for this problem.

**Comment by JeldorPKU** [comment]
Fixed through #297 .
