### ISSUE TITLE
Excel exporting not working.

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/CAPUrace#269]
Any volunteers to fix this? Too busy these days.

**Comment by JeldorPKU** [comment]
Maybe it's because we lack the following PHP extensions?
- PHP version 5.2.0 or newer
- PHP extension php_zip enabled [^phpzip_footnote]
- PHP extension php_xml enabled
- PHP extension php_gd2 enabled (if not compiled in)

**Comment by JeldorPKU** [comment]
Everything is fine in my local development environment, but the staffs say that they can only export empty file from the server. I believe the lack of extensions is our problem.

**Comment by JeldorPKU** [comment]
`GET https://race.chexie.net/index.php/admin/export net::ERR_INVALID_RESPONSE`
The browser gives me this information when I click the export button. @huxuan

**Comment by QwertyJack** [comment]
Just lack of `php-zip`.
Install it and restart; it works now.
BTW: db backup for capurace added

**Comment by JeldorPKU** [comment]
So we can close this issue now.

**Comment by QwertyJack** [comment]
Anyway, `php_gd2` means version of gd >= 2.0 .
Actually there is no `php-gd2` module available.

**Comment by huxuan** [comment]
Cool, thanks @QwertyJack
