### ISSUE TITLE
Customizing the CodeIgniter system.

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/capurace#3]
Make the CI system suitable for future developing, including:

1. Set up a connection between our code and the database.
2. Change the default language to Chinese (optional). 
3. Since there are lots of parts where we have to use `db` super object, we have to autoload it. 
4. Have the database structure settled. 
5. Remove useless directories like `user_guide` (optional).

**Comment by huxuan** [comment]
Feel free to leave the `user_guide` directory. I usually use it as offline docs which is more faster. There is no harm to leave it currently.
