### ISSUE TITLE
Export the data into csv file.

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/capurace#37]
After submitting the information to us and paid, users can download the `.csv` file for further use.

**Comment by JeldorPKU** [comment]
@zhzhzoo 能单独一个PR写这个功能吗？或者你把之前我revert掉的那个分支改改，昨天遇到的问题是小猴子登录之后其他人再登录就上不去了。我的建议是你把现在的代码拷贝一下，然后从现在最新的版本重开一个branch来写。

**Comment by zhzhzoo** [comment]
为什么登陆不上去呀~

**Comment by JeldorPKU** [comment]
难道不应该问你吗……反正所有人上去都是404
