### ISSUE TITLE
Seems we can't send mail to *@126.com?

### ISSUE THREAD

**Issue by huxuan** [CAPU-ENG/capurace#42]
![qq20150401-1 2x](https://cloud.githubusercontent.com/assets/726061/6927842/b1e0b5f4-d822-11e4-9548-38c6bf56ee8e.png)

**Comment by JeldorPKU** [comment]
Your vpn seems to be unable to connect to SMTP server of 126. I found this issue some time ago but I don't think this would happen on our server. Is this responsible for the problem you encountered with?

**Comment by huxuan** [comment]
No they are not the same problem. Actually it's a kind of protection to avoid sending spam within the same domain. Maybe we need to notify in the signup page.

**Comment by JeldorPKU** [comment]
Shall we use `capurace@pku.edu.cn` as the sending mailbox and set the `reply_to` to be `beidachexie!@126.com`? I think this should work.

**Comment by huxuan** [comment]
OK, I will do it soon.

**Comment by huxuan** [comment]
![image](https://cloud.githubusercontent.com/assets/726061/7017607/6ebbf2fc-dd2c-11e4-9dcc-fb58843f1d09.png)

**Comment by huxuan** [comment]
![image](https://cloud.githubusercontent.com/assets/726061/7017639/273c4df4-dd2d-11e4-9485-f0ad7dfeb13c.png)
![image](https://cloud.githubusercontent.com/assets/726061/7017687/b7db6250-dd2d-11e4-9537-110623367ed7.png)
![image](https://cloud.githubusercontent.com/assets/726061/7017702/fcb65948-dd2d-11e4-9c43-bf27fb5e1219.png)

**Comment by huxuan** [comment]
I have test pku mail by sending it to gmail/126 and qq, but as we have known, it failed when sending to other pku mails. I think we can close this issue now. I will deploy it on server.

**Comment by JeldorPKU** [comment]
Please set the `reply_to` mailbox as `beidachexie@126.com` in your PR.
