### ISSUE TITLE
报名须知？

### ISSUE THREAD

**Issue by huxuan** [CAPU-ENG/capurace#49]
报名页面首页需要一个文案性质的东西，只有当同意之后才可以继续报名，这个文案内容记得马丁之前提到过，有确切的内容了么？

**Comment by huxuan** [comment]
![snip20150401_2](https://cloud.githubusercontent.com/assets/726061/6940798/bbbb0a40-d8ac-11e4-99a3-c25d162f2e1d.png)

**Comment by JeldorPKU** [comment]
这个可以有

**Comment by cindywang319** [comment]
马丁表示今晚弄出来 明天我问他要

在 2015年4月1日，23:47，蒋雨蒙 <notifications@github.com> 写道：

**Comment by huxuan** [comment]
Please post the 《报名须知》 here just for more information.
