### ISSUE TITLE
Avoid skipping individual registration.

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/capurace#51]
Users now can directly type `race.chexie.net/registration/team/` to skip the individual registration.

**Comment by huxuan** [comment]
I would rather vote this for future enhancement.

As I have told you, we should imagine all users are not evil.

Even if we can add some check for it, evil guys can still hack it.

**Comment by JeldorPKU** [comment]
All right.

**Comment by huxuan** [comment]
I don't think this is a issue now. So close it.
