### ISSUE TITLE
当且仅当第一次登录显示报名须知

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/capurace#58]
每次点进报名都要看一次报名须知感觉不太好……

**Comment by huxuan** [comment]
我反而觉得报名须知应该每次都看的才好吧，虽然可能用户体验上是多了一步操作，但是作为报名的流程，确实就应该“麻烦”一点。

**Comment by huxuan** [comment]
As I have commented, I prefer judge it as necessary rather than viewing only the first time. So close this issue.
