### ISSUE TITLE
学习一下 migration 类似的思路（？）

### ISSUE THREAD

**Issue by zhzhzoo** [CAPU-ENG/capurace#63]
嗯思路比如 http://en.wikipedia.org/wiki/Schema_migration。
就是每次改变数据库模式，不改 capubbs.sql，而是添加新的 capubbs1.sql capubbs2.sql ...
每一个包含数据库修改语句，从而每次数据库改变模式不会使数据丢失

**Comment by huxuan** [comment]
Migration是很多框架都支持的，比如CI里的`application/config/migration.php`。我们没有这么做的原因是我们的规模没有必要这么做，现在没有真实的数据，内测之后确定了的数据结构就几乎不会再变了。我先关掉这个issue了，如果有什么疑问，请尽管reopen。
