### ISSUE TITLE
Registration models.

### ISSUE THREAD

**Issue by JeldorPKU** [CAPU-ENG/capurace#9]
The model to add or update people and team information into the database.

**Comment by huxuan** [comment]
Actually I don't think we need extra model for registeration. It should just be a User/School Model, isn't it?

**Comment by huxuan** [comment]
Sorry seems I have misunderstood it. It seems ok to me now.

**Comment by huxuan** [comment]
Seems this issue has also been fixed, right?

**Comment by huxuan** [comment]
@JeldorPKU Feel free to close this if you are OK with it.
