### ISSUE TITLE
手机号和身份证号验证

### ISSUE THREAD

**Issue by goodman-capu** [CAPU-ENG/capurace#92]
判断是否合理？比如手机号一定要是11位数字

**Comment by huxuan** [comment]
后台验证还没实现……

**Comment by goodman-capu** [comment]
这个需要后台验证吗？直接填写的时候通过js判断？

**Comment by JeldorPKU** [comment]
@goodman-capu js是可以被绕过的，所有后台验证都是必需的。这个issue关上了，你看看现有的issue，没有提过的再写上来。

**Comment by huxuan** [comment]
前台的意义不大，比如说别人可以写个脚本post数据……
