### ISSUE TITLE
Header挡住了部分内容

### ISSUE THREAD

**Issue by goodman-capu** [CAPU-ENG/capurace#93]
RT
![2015-04-15 1 57 18](https://cloud.githubusercontent.com/assets/8862302/7152953/6dd24d9a-e377-11e4-9535-46f8eed89d59.png)
![2015-04-15 1 57 42](https://cloud.githubusercontent.com/assets/8862302/7152956/7e40ffb4-e377-11e4-8b53-bfe3141a24e5.png)

**Comment by huxuan** [comment]
是谁把style.css里body的padding-top给删了……

**Comment by huxuan** [comment]
![image](https://cloud.githubusercontent.com/assets/726061/7154351/b6cadcdc-e387-11e4-85ab-c74647becdf3.png)

**Comment by JeldorPKU** [comment]
@goodman-capu 轮到你来做贡献了！

**Comment by huxuan** [comment]
这个是千爷修改的，可能是跟首页的内容冲突了，可以在registration的页面外面都包一层，`<div class='reg-body'>`，然后css里`.reg-body {padding-top: 70px}`应该就行了。

**Comment by cindywang319** [comment]
我提交了个pr解决这个问题 我关掉这个issue咯
